### ISSUE TITLE
Links in chat opening in Safari on iOS 10 even though they can be opened in app

### ISSUE THREAD

**Issue by dangochi** [zendesk/zendesk_sdk_chat_ios#119]
- SDK version: 1.3.2.1
- Xcode version: 8.0
- iOS or Simulator: both
- iOS Version: 10.0.2
- Swift version: n/a

Steps to Reproduce:
1. have agent paste link into chat and send to user
2. try to open the link from device as the user
3. notice link gets opened in Safari even though it can be opened in app

In iOS 8 and 9 this works correctly, but in iOS 10 I'm not getting the same behavior. We override UIApplication's `openURL:` methods in our app to handle our website's URLs and convert them to URLs that our app can handle.

If I set a breakpoint in the `openURL:` methods, I see it hit in iOS 9, but I don't see either of them hit in iOS 10.

**Comment by StevenDiviney** [comment]
Hi @dangochi,

I have spent a bit of time investigating this. openURL: has been deprecated in iOS10 and replaced with openURL:options:completionHandler:. I tried overriding the new method but that does not seem to get called either. Beyond that I'm not sure what the problem is.

I have created an issue for us to track this internally.

**Comment by sspitzer** [comment]
@StevenDiviney any updates?

**Comment by baz8080** [comment]
@sspitzer The issue is in our backlog. It has not been scheduled into a patch yet.

**Comment by baz8080** [comment]
@sspitzer This is tracked internally, and we'll aim to address it in Chat SDK V2, which is in active development. We won't be patching it in V1, sorry!
