### ISSUE TITLE
Anonymous chat without email

### ISSUE THREAD

**Issue by TofPlay** [zendesk/zendesk_sdk_chat_ios#131]
- SDK version: 1.3.2.1
- Xcode version: 8.2.1 (8C1002)
- iOS or Simulator: 10.0
- Swift version: 3.0.2

Steps to Reproduce:

1. Set to an existing user
```swift
      ZDCChat.updateVisitor {
        (pVisitor:ZDCVisitorInfo?) -> Void in
        
        if let lVisitor = pVisitor {
          lVisitor.email = "john.doe@gmail.com"
          lVisitor.name =  "John Doe"
          lVisitor.phone = ""
        }
      }
``` 
2. Start a chat
3. Check on the web admin you will see the name "John Doe" with the email "john.doe@gmail.com"
4. Close the chat
5. Update visitor as an anonymous user:
```swift
      ZDCChat.updateVisitor {
        (pVisitor:ZDCVisitorInfo?) -> Void in
        
        if let lVisitor = pVisitor {
          lVisitor.email = ""
          lVisitor.name =  "Anonymous"
          lVisitor.phone = ""
        }
      }
``` 
6. Start the chat
7. Check on the web admin you will see the name "Anonymous" with the email "john.doe@gmail.com"

Expected: 
Check on the web admin you will see the name "Anonymous" with the email ""

**Comment by mathewcropper** [comment]
Hi @TofPlay. Thanks for flagging this. I actually have it in my list of to-do items to update our docs with instructions on how to clear a previous identity.

I don't have the details to hand right now, but will come back to you later today. Sorry for the wait.

**Comment by mathewcropper** [comment]
Hey @TofPlay. Sorry for the delay in updating here. It turned out that this wasn't a documentation issue, but is actually an issue with the way that we integrate with Chat. To deal with this, we'll need to go back to the drawing board and figure out how to deal with this undesirable behaviour.

I'll change the tag of this issue to bug and add it to our backlog. We don't currently have a release planned for the Chat SDK, so I can't say what the timeline will be for this, I'm afraid.

**Comment by hemangshah** [comment]
@mathewcropper , Is this issue has been fixed?

**Comment by baz8080** [comment]
@hemangshah It has not. We'll update the issue when it is. We are planning on doing work on chat in the new year.

**Comment by baz8080** [comment]
Hi, I'm going to close this. We have an issue tracked internally and targeted for Chat SDK V2.
