### ISSUE TITLE
No push notification if user has app minimized or off. To allow user to go back to app.

### ISSUE THREAD

**Issue by felixdkatt** [zendesk/zendesk_sdk_chat_ios#24]
The app should have something in the init to allow you to pass in your notifcation token and your app URL to ping the user so they can get a notification and then get into the app directly back to chat window with URL deeplink

**Comment by tecknut** [comment]
Hi @felixdkatt, Chat SDK doesn't currently provide push notifications. 

Can you describe what you want in some more detail please? We want to be sure we understand what you mean.

**Comment by degterev** [comment]
Hi @tecknut @oarrabi  
We want to send push-notification to our application when the application is standby. 
For example: our user is making conversation with our support team and stay to wait the answer and lock the phone. For updating this user wiht new message, when the phone is locked, we can send the push-notification.

Due to the list of features of Chat SDK you don't have any solutions for such cases? Or I wrong

Thanks
@schlan hope you will be interested

**Comment by baz8080** [comment]
Hi @degterev 

This will be possible when we support push notifications, but we do not support them yet.

**Comment by eugenemakarenko** [comment]
Okey @baz8080 
Maybe you can provide another way for updating information into the chat-on when the App is stanby (for example webhooks)? Or maybe do you have information about start support of push-notifications?

**Comment by oarrabi** [comment]
Hello @eugenemakarenko, I am afraid we don't have a clear timeline on when push notifications are getting added to chat. Also we don't have webhooks for chat at the moment.

I will keep this issue open and update you when we have added either push or webhooks.

**Comment by mathewcropper** [comment]
Hi there. I'm Mat, the Product Manager for our SDKs. I'd like to give you an update.

A few people have asked for push notifications as a feature in the Chat SDK. It's not something we are planning to add any time soon, for several reasons. The main one for me is that tickets are a more effective way of handling asynchronous conversations right now, and that feature supports push notifications. Additionally, as chat sessions time out after five minutes, a push notification that is tapped after this limit has been reached would result in a terrible end-user experience (follow push, get closed chat). There are wider user experience questions that need to be handled in order to make this a truly useful feature.

I'll close this issue on that basis, with thanks for sharing your feedback. If you would like to share other ideas in future, the best place is in one of our Zendesk communities, where it will have a broader reach and discussion. I'd suggest either the [Zendesk SDKs community](https://support.zendesk.com/hc/en-us/community/topics/200488257-Zendesk-SDKs) for feature requests specific to the SDK, or the [Product feedback community](https://support.zendesk.com/hc/en-us/community/topics/200132066-Product-feedback) for more general ideas.

**Comment by felixdkatt** [comment]
We disagree and have decided to not use your product and go with another that supports it.
