### ISSUE TITLE
[question] Is it possible to implement a chat interface, without using the ZD ui classes?

### ISSUE THREAD

**Issue by vbrittes** [zendesk/zendesk_sdk_chat_ios#36]
I'd like to custom the chat and overlay interface beyond the UIAppearence capabilities.

**Comment by schlan** [comment]
Hi @vbrittes, please, can you share more information about how you want to customise the chat overlay?

**Comment by vbrittes** [comment]
It would be nice if I could subclass the zd view used currently to layout the overlay or to implement a protocol, so the required attributes to display the incoming messages relevant information would still be available, and it would also be possible to custom its layout without interfering the zopim core implementation. 
The custom layout would be something like placing and image view containing an icon that makes sense within the app context instead of only a white square, custom the label where the message count is shown, or even changing the layer corner radius.

**Comment by schlan** [comment]
Hi @vbrittes, thanks for clarifying. I added this as a feature request to our backlog, we'll keep you updated here.

**Comment by ndobri** [comment]
Hi @vbrittes, 
I am very sorry that we've missed to give you an update once this issue was resolved with [1.2.0.1](https://github.com/zendesk/zendesk_sdk_chat_ios/releases/tag/1.2.0.1). See our [customization docs](https://developer.zendesk.com/embeddables/docs/ios-chat-sdk/customization#styling-your-chat-ui).
Nevertheless, I hope that you'll find this information useful. Closing this issue.
