### ISSUE TITLE
startchat stuck

### ISSUE THREAD

**Issue by ajijoyo** [zendesk/zendesk_sdk_chat_ios#72]
run zopimchatsample on device, first startchat working fine, but when endchats then startchat again, get stuck CPU run up to 99%
<img width="259" alt="screen shot 2016-03-19 at 5 56 06 pm" src="https://cloud.githubusercontent.com/assets/10805529/13898193/4fca9f4c-edfc-11e5-8d9f-5c4008c77104.png">
but on simulator is working fine.

(im using device iphone 5 ios 9.2)

im sorry my english is not good enough

**Comment by oarrabi** [comment]
Hello @ajijoyo 

Thanks for raising this issue with us. We were able to reproduce this issue on our end.
I created a ticket to track this issue internally and will release a patch when we fix this.

The issue happens when calling `[[ZDCChat instance].session trackEvent:@"Event"];` on a 32 bit device (any iPhone before 5s). Until we release a patch, please dont use this method as it will block the UI.

Thanks for reaching us, and sorry for any inconvenience this might have caused you :)

**Comment by ajijoyo** [comment]
thanks @oarrabi

**Comment by oarrabi** [comment]
Hello @ajijoyo,

We just released `ZDCChat` version 1.2.1.1 which has a fix to this issue.
Please check it out and let us know.

Thanks,
Omar...

**Comment by oarrabi** [comment]
I am going to close this for now, if you are still experiencing the issue, please feel free to reopen it
