### ISSUE TITLE
No accessibility / voice over support?

### ISSUE THREAD

**Issue by rsaunders100** [zendesk/zendesk_sdk_chat_ios#81]
If I am not mistaken the SDK does not support voice over?  This means any app that uses your SDK will not be accessible.

Please can you support accessibility

**Comment by ndobri** [comment]
Hi there and thank you for reporting this to us. 

I can confirm for now that we'll add it as a feature request and it will be in planning for our future releases. We can't give an ETA, but we will update this issue once we have more news about this feature.

**Comment by mathewcropper** [comment]
Hi there. I'm Mat, the Product Manager for our SDKs. I'd like to give you an update.

Accessibility across our SDKs is something that is on my mind, but there are no plans in the short term to make changes. As this is a broad theme, rather than a specific individual feature, I'd like to close this issue and convey my thanks for raising it. I'm sorry that our SDK doesn't currently provide the accessibility support that you expect, but it is something we will revisit in the future.

I'll close this issue on that basis, with thanks for sharing your feedback. If you would like to share other ideas in future, the best place is in one of our Zendesk communities, where it will have a broader reach and discussion. I'd suggest either the [Zendesk SDKs community](https://support.zendesk.com/hc/en-us/community/topics/200488257-Zendesk-SDKs) for feature requests specific to the SDK, or the [Product feedback community](https://support.zendesk.com/hc/en-us/community/topics/200132066-Product-feedback) for more general ideas.
