### ISSUE TITLE
Is it possible to set the tint of the alerts that pop up?

### ISSUE THREAD

**Issue by jstheoriginal** [zendesk/zendesk_sdk_chat_ios#88]
Example the Email Transcript and confirm end chat alerts...we have the tint color set to a red color in our app delegate, but the colour is the default blue when using Zendesk in the app.

**Comment by oarrabi** [comment]
Hello @jstheoriginal 

Since we are still using `UIAlertView` for compatibility issues, there is no legal way to customize (apple normally frowns on customizing it). However, we are in the process of rewriting part of the SDK UI, when that's done, we will allow the customization of it. 

I will log an issue in our internal bug tracker to follow up with this.

Thanks.

**Comment by mathewcropper** [comment]
Hi there. I'm Mat, the Product Manager for our SDKs. I'd like to give you an update.

I'm in the process of updating issues in Github after reviewing our roadmap. At the moment, we don't have plans to make changes to the Chat SDK's UI to add additional theming options. As @oarrabi says, we may revisit this in the future, but it is not something that's in the plan for the short to medium term.

I'll close this issue on that basis, with thanks for sharing your feedback. If you would like to share other ideas in future, the best place is in one of our Zendesk communities, where it will have a broader reach and discussion. I'd suggest either the [Zendesk SDKs community](https://support.zendesk.com/hc/en-us/community/topics/200488257-Zendesk-SDKs) for feature requests specific to the SDK, or the [Product feedback community](https://support.zendesk.com/hc/en-us/community/topics/200132066-Product-feedback) for more general ideas.
