### ISSUE TITLE
get status of agent availability before opening chat session

### ISSUE THREAD

**Issue by mradamfrancis** [zendesk/zendesk_sdk_chat_ios#94]
I'd like to know before opening a chat session if an agent is online/ offline. Is that possible with current version of SDK?

**Comment by StevenDiviney** [comment]
@mradamfrancis You have to connect to a chat session before you can determine if an agent is online / offline. You can do this using the [API](https://developer.zendesk.com/embeddables/docs/ios-chat-sdk/sessionapi). Once a chat session has connected you can determine if their are any agents online by using [accountOnline](https://github.com/zendesk/zendesk_sdk_chat_ios/blob/4ec4f606b62325482dac975378bce49b42627b77/ZDCChat.framework/Headers/ZDCChatDataSource.h#L106)

If you then load the UI it will connect to the session in progress.

**Comment by ndobri** [comment]
Hi @mradamfrancis,
Since we haven't heard from you in a while, I am going to tentatively close this issue. Please feel free to reopen this issue if you have further questions about the way to discover account online status.

**Comment by zipme** [comment]
hi @ndobri @StevenDiviney 

It seems `ZDCChatAPI.instance().agents` only returns agents who are VIEWING the requests instead of just online agents. 

Is there a way to get agents who are online (regardless they are viewing requests or not), and it'd be better if we don't need to start a session before we can get this info. We have a button in the app which triggers the chat and it's only enabled when at least one agent is available, I am currently start a session in the background when the app starts which I think is kind of ugly. Any suggestions?

**Comment by zipme** [comment]
okay, I think it's because the ZDCChatAPI.instance().agents only display agents for a certain chat session instead of all the available agents who are currently online.

It would be cool if `ZDCChatAPI.instance().agents` returns all available agents and have something like `ZDCChatAPI.instance().activeSessions` to return something like `[ZDCChatSession]`, and `ZDCChatSession` has a property `agents`

**Comment by apascual** [comment]
Hi, is there any update on this?

We would like to redirect users to the chat or the normal support depending on the chat availability.

**Comment by alpen89** [comment]
Hello, I'm with @apascual on this. To check if agents are online, we have to open a chat session. So let's imagine we would do it in the background on app start only to check if any agents are online, so we can decide to show chat or other support. Now there would be avg. 13000 open chat sessions from our app only in a day just to check if any agents are available. 

Do you think that this is going to be a problem? @divo and @ndobri 
I personally don't find this approach perfect, as it also changes the "start chat/ continue conversation" chat button status.

Please let me know on your thoughts.
Thank you!
