### ISSUE TITLE
Chat loaded via push disables Back/End chat action when exiting and revisiting chat again 

### ISSUE THREAD

**Issue by Esthove** [zendesk/zendesk_sdk_chat_ios#95]
I updated yesterday to version 1.2.1.1 and found the below.
When the chat view is loaded via push and during a chat if you hit "Back" and go to the previous controller and come back to chat again, the "Back" and "End chat" button action no longer works.

I downgraded the sdk to 1.2.0.1 and found that to be working properly again. 
Can you please verify what has changed relating to it in 1.2.1.1 ?

**Comment by StevenDiviney** [comment]
@Esthove Thanks for bringing this to our attention. We changed the behavior to fix a bug where popViewController would be called twice but introduced this issue. 

It only happens when presenting the chat in a nav controller without the overlay enabled. If you present it modally or use the overlay this will not happen. I have created an issue internally for us to track this and we will update you when it has been released.

**Comment by Esthove** [comment]
Thanks Steven for acknowledging it. I present chat using the nav controller having overlay disabled just like you mentioned. Using a modal view doesn't align with our design as it tends to breaks the navigation bar styling. For now I am moving ahead with 1.2.0.1 and hope the issue be resolved soon as per your priority.

**Comment by ndobri** [comment]
@Esthove this was fixed in [Chat SDK 1.3](https://github.com/zendesk/zendesk_sdk_chat_ios/releases/tag/1.3.0.1). Closing this issue now, but if it is not resolved for you please feel free to let us know by reopening this thread.
